version: '3.8'

services:
  app:
    image: ha-video-parser:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    user: parser:parser
    volumes:
      - .:/app
    tty: true
